### ISSUE TITLE
Thrown errors in application are caught by underlying amqplib (using callback api)

### ISSUE THREAD

**Issue by jcrugzz** [amqp-node/amqplib#123]
So i was doing some tests with my [`rabbit-rr`](https://github.com/jcrugzz/rabbit-rr) library which wraps `amqplib` similar to `rabbit.js` (aside: i just needed the callback interface req/rep but THANK YOU for all your reference code). What I ran into while doing some tests (with some bad asserts in the tests at the time) was that the `amqp` library itself grabbed the thrown error from the assert and emit the error event itself.

Example can be found below where I put a `console.dir(msg)` [here](https://github.com/squaremo/amqp.node/blob/master/lib/channel.js#L236) and add a bad assert to one of my tests.

and receive the following stack from the [`assume`](https://github.com/bigpipe/assume) library I'm using.

The output of the message is followed by an output of the arguments passed to the function invoked in the `else` clause.

``` sh

{ message: 'Unknown assertation failure occured, assumed `undefined` to be truthy',
  stack: 'Unknown assertation failure occured, assumed `undefined` to be truthy 
   /Users/jcrugzz/github/jcrugzz/rabbit-rr/test/simple.test.js
    .on(\'message\', function (msg, reply) { 
      assume(msg.bar).is.ok();
      assume(msg).is.an(\'object\');
      at Assert.ok (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/assume/index.js:277:15)       
      at RepSocket.<anonymous> (/Users/jcrugzz/github/jcrugzz/rabbit-rr/test/simple.test.js:108:28)      
      at RepSocket.emit (events.js:98:17)
      at RepSocket._consume (/Users/jcrugzz/github/jcrugzz/rabbit-rr/socket.js:9:8990)      
      at Channel.BaseChannel.dispatchMessage (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:459:12)
      at Channel.BaseChannel.handleDelivery (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:468:15)
      at Channel.emit (events.js:95:17)\n at /Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:260:10
      at Channel.content [as handleMessage] (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:313:9)
      at Channel.C.acceptMessageFrame (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:226:31)      
      at Channel.C.accept (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:381:17)     
      at Connection.mainAccept [as accept] (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/connection.js:62:33)
      at Socket.go (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/connection.js:465:48)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:426:10)
      at emitReadable (_stream_readable.js:422:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:528:21)\n\u001b[0m' }
{ '0': 'Internal error while processing message',
  '1': 541,
  '2': [Error: [object Object]] }
```

Typically this occurs when the function invocation is happening in a try catch but I'd love your thoughts into how this could be resolved @squaremo. Definitely interested in helping :smile:

**Comment by squaremo** [comment]
I see, so the assume library is `throw`ing an object, and that's not accounted for in the `if .. then .. else`. I'm not sure what it should do, though, since this is happening in a callback. I guess the alternatives is to let thrown objects 'splode everything.

What does `assume` assume is going to happen?

(Some prior discussion of using exceptions: https://github.com/squaremo/amqp.node/issues/8, https://github.com/squaremo/amqp.node/issues/56.)

**Comment by jcrugzz** [comment]
@squaremo So assume is doing what any old assert does. throw an error when something does not satisfy the condition. THe problem is that this is being caught by the underlying `amqp.node` library because the state machine is running in a `try..catch`. This just shows that any application error that is thrown gets caught by the state machine `try..catch` which I find to be unexpected as there is not a way to handle this. Ive seen this cause other issues when using the `node_redis` (which calls certain callbacks in a `try..catch`) library which is why I bring this up.

My thought that I was getting at in my PR was to replace unneeded try catch logic with a pattern that can handle asynchronous error cases correctly and end gracefully without impeding anything on the application layer.

**Comment by cressie176** [comment]
The difficulty is that amqplib will never have sufficient context about the error to make an informed decision what to do. For example, on detecting an error, should it acknowledge, reject or re-queue the message? But equally it should do something as an unhandled error will crash the entire application. Errors get harder (or even impossible) to handle when thrown from asynchronous code.

Given the complexities, the blunt and incomplete approach taken by amplib is reasonable and pragmatic, i.e. catch synchronous errors, break the channel and emit an error. Anything more is up to the application developer to handle, however the approach can cause headaches when testing.

Mocha (and hopefully other popular test frameworks) catch unhandled errors, so providing you use the amqplib Callback API in conjunction with Mocha's done callbacks, the following test fails as expected...
```javascript
  it('should handle exceptions', (done) => {
    connection.createConfirmChannel((err, channel) => {
      if (err) return done(err);
      channel.sendToQueue('test', Buffer.from('foo'), {}, (err) => {
        if (err) return done(err);
        const consumerTag = `X-${Math.random()}`;
        channel.consume('test', (msg) => {
          channel.cancel(consumerTag, (err) => {
            if (err) return done(err);
            assert.equal(msg.content.toString(), 'bar');
            done();
          })
        }, { noAck: false, consumerTag }, (err) => {
          if (err) return done(err);
        })
      })
    })
  })
```
```
issue-123
    1) should handle exceptions


  0 passing (51ms)
  1 failing

  1) issue-123
       should handle exceptions:

      Uncaught AssertionError [ERR_ASSERTION]: 'foo' == 'bar'
      + expected - actual

      -foo
      +bar
      
      at /Users/steve/Development/cressie176/amqplib-123/test.js:39:20
      at /Users/steve/Development/cressie176/amqplib-123/node_modules/amqplib/lib/callback_model.js:59:7
      at /Users/steve/Development/cressie176/amqplib-123/node_modules/amqplib/lib/callback_model.js:202:9
      at reply (node_modules/amqplib/lib/channel.js:106:16)
      at ConfirmChannel.C.accept (node_modules/amqplib/lib/channel.js:451:12)
      at Connection.mainAccept [as accept] (node_modules/amqplib/lib/connection.js:64:33)
      at Socket.go (node_modules/amqplib/lib/connection.js:478:48)
      at emitReadable_ (internal/streams/readable.js:555:12)
      at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
What's happened is that even through the consumer callback went asynchronous, and the amqplib try/catch block was bypassed, Mocha has intercepted the unhandled assertion error and reported it.

However, if you switch to the Promises API and async functions the test passes unexpectedly
```javascript
  it('should handle exceptions', async () => {
    const channel = await connection.createConfirmChannel();
    channel.sendToQueue('test', Buffer.from('foo'));
    await channel.waitForConfirms();

    const consumerTag = `X-${Math.random()}`;
    await channel.consume('test', async (msg) => {
      await channel.cancel(consumerTag);
      assert.equal(msg.content.toString(), 'bar');
    }, { noAck: false, consumerTag });
  });
```
```
  issue-123
    ✔ should handle exceptions


  1 passing (36ms)
```
This is because there is nothing to tell Mocha to wait for the assertion, and therefore the test may complete before the assertion fails. My preferred workaround is to mix the amqplib Promises API with mocha's done callbacks follows...

```javascript
  it('should handle exceptions', (done) => {
    (async () => {
      const channel = await connection.createConfirmChannel();
      channel.sendToQueue('test', Buffer.from('foo'));
      await channel.waitForConfirms();

      const consumerTag = `X-${Math.random()}`;
      await channel.consume('test', async (msg) => {
        try {
          await channel.cancel(consumerTag);
          assert.equal(msg.content.toString(), 'bar');
          done();
        } catch (err) {
          done(err)
        }
      }, { noAck: false, consumerTag });
    })();
  });
```
```
  issue-123
    1) should handle exceptions


  0 passing (44ms)
  1 failing

  1) issue-123
       should handle exceptions:

      AssertionError [ERR_ASSERTION]: 'foo' == 'bar'
      + expected - actual

      -foo
      +bar
      
      at channel.consume.noAck (test-a.js:31:18)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
It's not perfect, but I don't think we can should stop amqplib catching exceptions thrown synchronously from the consumer callback.
