### ISSUE TITLE
How to use assertExchange and assertQueue the same time

### ISSUE THREAD

**Issue by NguyenTungs** [amqp-node/amqplib#255]
I have code :
###### file emit_log_direct.js

``` bash
var amqp = require('amqplib/callback_api');


amqp.connect('amqp://localhost', function(err, conn) {
    conn.createChannel(function(err, ch) {
        var ex = 'direct_logs';
        var q = 'qqqq';
        var count = 0;
        args = ['java', 'php'];
        setInterval(function() {
            ++count;
            //var msg = 'Nguyen Tung' + count;
            ch.assertExchange(ex, 'direct', { durable: false });
            ch.assertQueue(q, { durable: false });

            args.forEach(function(severity) {


                console.log('severity', severity);
                var msg = 'Nguyen Tung ' + count;
                ch.publish(ex, severity, new Buffer(msg));
                ch.sendToQueue(q, new Buffer(msg),{ persistent: true });
                console.log(" [x] Sent %s: '%s'", severity, msg);

            });


        }, 2000);
    });
});
```
###### file receive_log_direct.js

``` bash
var amqp = require('amqplib/callback_api');

var args = process.argv.slice(2);

if (args.length == 0) {
    console.log("Usage: receive_logs_direct.js [info] [warning] [error]");
    process.exit(1);
}

console.log('args',args);
amqp.connect('amqp://localhost', function(err, conn) {
    conn.createChannel(function(err, ch) {
        var ex = 'direct_logs';
        var q = 'qqqq';

        ch.assertExchange(ex, 'direct', { durable: false });

        ch.assertQueue('', {durable: true, autoDelete: false, confirm: true}, function(err, q) {
            ch.prefetch(1);
            console.log(' [*] Waiting for logs. To exit press CTRL+C');

            args.forEach(function(severity) {
                ch.bindQueue(q.queue, ex, severity);
            });

            ch.consume(q.queue, function(msg) {
                ch.ack(msg);
                console.log(" [x] %s: '%s'", msg.fields.routingKey, msg.content.toString());
            }, { noAck: false });
        });
    });
});
```

why show log in terminal.

 [x] qqqq: 'Nguyen Tung 279'
 [x] java: 'Nguyen Tung 280'
 [x] qqqq: 'Nguyen Tung 280'

i want : 
shell1: java: 'Nguyen Tung 280'

shell2: php: 'Nguyen Tung 280'

**Comment by cressie176** [comment]
Sorry @NguyenTungs, I'm really not sure what behaviour your trying to achieve, but a couple of things which looked odd...

1. The calls to assertExchange and assertQueue aren't always nested. This means that you might attempt to use them before they are asserted into existence.
2. Your two processes appear to use the same queue but define different parameters

I suspect the reason you're seeing ```qqqq``` in your log output is because you are publishing messages directly to a queue. If you read [amqp concepts](https://www.rabbitmq.com/tutorials/amqp-concepts.html), you'll find that when you send a message directly to a queue, rabbit actually publishes the message to the 'default exchange', using the queue name for the routing key. All queues are automatically bound to the default exchange using their name, hence why you're getting extra messages in your output.
