### ISSUE TITLE
Channel.close() appears to throw instead of reject

### ISSUE THREAD

**Issue by jim-cooper** [amqp-node/amqplib#257]
It seems that if an error occurs in `channel.close()` that it throws instead of rejecting the promise.  You can see this by attempting to close an already closed channel and then you are unable to use `.catch()` to catch the rejected promise.

**Comment by yiooxir** [comment]
+  
wtf. I can't close channel and go ahead after i don't need in it.

**Comment by squaremo** [comment]
The general pattern is that errors from the server are given as promise rejections, while usage errors (closing a channel more than once) are exceptions.

Since it's often tricky -- or at least, more work -- to arrange for a channel to only be closed once, I can see the argument for that being either idempotent (works the first time, and trivially succeeds afterwards), or rejecting the promise. Which would be more convenient?

**Comment by cressie176** [comment]
Closing as very old
