### ISSUE TITLE
release major version 1.0.0

### ISSUE THREAD

**Issue by anoff** [amqp-node/amqplib#327]
using this library quite often. With 200k dl/month I was wondering if it wasn't time to switch to full semver compatibility with a major release of 1.0.0.
Are there any missing features you think need to be resolved until a _stable_ version can be released?

background: bumping semver for <1.0.0 versions is annoying :(

**Comment by michaelklishin** [comment]
SemVer is a means, not an end.

This client has been around long enough that a 1.0.0 wouldn't be unreasonable but I don't see significant breaking changes happening already.

Switching to SemVer has one very real downside for the maintainer: with just about any breaking change you either have to bump major version or spend a lot of time in mostly meaningless conversations about what constitutes a major vs. minor API change. So I can see why not switching to SemVer while the library is already quite stable can be appealing.

**Comment by anoff** [comment]
> with just about any breaking change you [..] have to bump major version [..]

@michaelklishin I don't see the downside on this. It should be pretty clear what a breaking API is, isn't it? I think developers are sometimes afraid of major version updates as _breaking_ has a bad smell. However projects like Chrom(ium) bump major regularly and I personally just like the added level of transparency and ease of use for the users. For < 1.0.0 releases there is no clear pattern what any version bump means for the user.

But you are right, the client has been around long enough and this is just supposed to bring up the idea of going semver. Don't want to force my opinion onto the maintainer.

That said, if I had an alternative I would always go for semVer compatible modules.

**Comment by squaremo** [comment]
I am just afraid of blessing anything as 1.0! :)

Having said that, I have not changed the API for a long time, and have been fairly careful already about not introducing breaking changes. So it wouldn't really change much for me.

**Comment by ebdrup** [comment]
I definately vote for a v1.0.0.
Since you can't trust semver 0.x regarding breaking changes.

https://semver.org/
`4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.`

I just had to spend  time investigating if anything was changed since v0.5.3, because we upgraded node, and the engines specification was complaining. 
If this module was at v1+ I could trust the semver and upgrade with no time spend on investigating (we have automated tests also).
