### ISSUE TITLE
Channel.consume doesn't wait before consuming again

### ISSUE THREAD

**Issue by blanchma** [amqp-node/amqplib#360]
```channel.consume(QUEUE_IN, function(msg) {
            FromRab.consume(msg).then( function(msg, error) {
              console.log("Msg",msg,"consumed. Error", error);
              if(error) {
                return false;
              } else {
                channel.ack(msg);
                return true;
              }
            })
          }, { noAck: true });

```

The consume function doesn't wait and consume too fast to my infra capacity. Anyway to prevent this?

**Comment by michaelklishin** [comment]
@blanchma see [tutorial 2](http://www.rabbitmq.com/tutorials/tutorial-two-javascript.html).

**Comment by michaelklishin** [comment]
as well as [documentation on acknowledgements](http://www.rabbitmq.com/confirms.html) and channel QoS.

**Comment by raeffray** [comment]
Channel.consume as promise and a callback is sent to work the messages. So when we receive the promise result not necessarily mens the message handler received all the message present in a certain queue. What is the correct time to close the channel?

**Comment by cressie176** [comment]
Closing, as very old. However my 2c...

> The consume function doesn't wait and consume too fast to my infra capacity. Anyway to prevent this?

By enabling explicit acknowledgements and setting a prefetch limit

> Channel.consume returns a promise and a callback is sent to work the messages. So when we receive the promise result not necessarily mens the message handler received all the message present in a certain queue. What is the correct time to close the channel?

I'm not aware of anything in the AMQP specification or this library that will automatically cancel a consumer when a queue is drained. Some options you may consider...

1. Repeatedly calling channel.get instead of using channel.consume
2. Publishing a "header" message that contains the number of messages you need to consume, and keeping track of the number of messages still remaining
3. Publishing a "terminator" message that indicates to the consumer when the last message has been delivered

If you're not careful 2 and 3 will rely on message order, which means unless you take additional precautions you cannot process messages concurrently (either from multiple processes, or within the same node process)
