### ISSUE TITLE
Unclear error handling cases.

### ISSUE THREAD

**Issue by ghost** [amqp-node/amqplib#377]
Hi,

This isn't an issue in the SDK but more of a documentation issue.  

I am unclear about how how to handle publishing/sending errors if the connection is killed by the server. For example if I publish or send 15 messages and the the connection is killed at some point, it is the connection that emits the error event not the channel. How am I to detect which messages were successfully published/sent and which ones were not?

If I used ConfirmChannels I could maybe have a timeout on the ack/nack and if that timeout expires assume the publish/send failed?

Thanks
Dan.

**Comment by cressie176** [comment]
Hi Dan,

I don't think you can be 100% sure. My 'goto' approach is to make sure messages I don't want to lose are persisted somewhere before I publish them, and tick them off once I receive the confirmation.

I usually have one process persisting the messages in a DB (say postgres) and another watching the table and publishing them.

If there are a large number / high frequency of messages then it's advisable to use table partitioning (assuming Postgres) and also SKIP LOCKED when polling the table for new messages.

The above also assumes the downstream systems can tolerate duplicate messages, but try to minimise this by blocking shutdown (e.g. due to redeployment) while I have messages waiting for publication.
