### ISSUE TITLE
Make it possible to disable heartbeats

### ISSUE THREAD

**Issue by carlhoerberg** [amqp-node/amqplib#467]
It's currently not possible to disable heartbeats, if you set a heartbeat value of 0 on the client side it will use the server's suggested value instead of disabling it (sending 0 to the server in the TuneOk frame). 

https://github.com/squaremo/amqp.node/blob/6ee18f27e31863f5256bc921a21f36ebf2ba5e74/lib/connection.js#L192-L198

**Comment by carlhoerberg** [comment]
This is how the Ruby lib bunny makes it: 

https://github.com/ruby-amqp/bunny/blob/f29c8b7deea72a04efbe81fd244a224757403d5f/lib/bunny/session.rb#L1187-L1191

**Comment by squaremo** [comment]
> if you set a heartbeat value of 0 on the client side it will use the server's suggested value instead of disabling it

That's what it's supposed to do. See [Matthias's explanation in #83](https://github.com/squaremo/amqp.node/pull/83#issuecomment-50988301).

**Comment by carlhoerberg** [comment]
No it's not because that would mean there's no way to disable heartbeats.
Almost all other client libraries supports that. If the client configures
heartbeat to 0 that should be sent to the server in the TuneOk frame, only
if the user didn't configured a heartbeat should the server's suggested
heartbeat interval be used.

**Comment by cressie176** [comment]
@robross0606,

It looks to me like the documentation you linked to contradicts itself. A little higher up it also states

> A zero value indicates that a peer suggests disabling heartbeats entirely. To disable heartbeats, both peers have to opt in and use the value of 0.

I've unfamiliar with erlang, but the [server code](https://github.com/rabbitmq/rabbitmq-server/blob/7abf749a60458aba9d6c9e6bdec1d3b0b2254007/deps/amqp_client/src/amqp_network_connection.erl#L239-L252)  this appears to confirm this is what was implemented...

```erlang
tune(#'connection.tune'{channel_max = ServerChannelMax,
                        frame_max   = ServerFrameMax,
                        heartbeat   = ServerHeartbeat},
     #amqp_params_network{channel_max = ClientChannelMax,
                          frame_max   = ClientFrameMax,
                          heartbeat   = ClientHeartbeat}, State) ->
    [ChannelMax, Heartbeat, FrameMax] =
        lists:zipwith(fun (Client, Server) when Client =:= 0; Server =:= 0 ->
                              lists:max([Client, Server]);
                          (Client, Server) ->
                              lists:min([Client, Server])
                      end,
                      [ClientChannelMax, ClientHeartbeat, ClientFrameMax],
                      [ServerChannelMax, ServerHeartbeat, ServerFrameMax]),
```

If I interpret the above correctly, when either or both the client and server value are zero, then the maximum of the two will be used, otherwise the minimum value will be used. i.e.

| client | server | calculation | result |
|------|--------|------------|------|
| 0       | 0          | max(0, 0)   | 0 |
| 1       | 0          | max(1, 0)    | 1 |
| 0       | 1         | max(0, 1)    | 1 |
| 1        | 2        | min(1, 2)     | 1 |
| 2        | 1        | min(2, 1)     | 1 | 

So the only way to disable heartbeats is by setting both the client and server to zero. For interest, the same [issue](https://github.com/rabbitmq/rabbitmq-erlang-client/issues/112) was reported with the erlang client, and they reached the same conclusion.

**Comment by robross0606** [comment]
Sheesh, you’d think they would have updated and clarified the documentation by now if this is something _so_ legacy that it cannot be changed in code. 😑

**Comment by cressie176** [comment]
I agree. I've raised the following https://github.com/rabbitmq/rabbitmq-website/issues/1386

Going to close this as the behaviour is out of amqplibs' control

**Comment by lukebakken** [comment]
> Sheesh, you’d think they would have updated and clarified the documentation by now if this is something so legacy that it cannot be changed in code.

@robross0606 perhaps it was just overlooked. The RabbitMQ docs are open-source so there is plenty of opportunity for users to contribute.

**Comment by carlhoerberg** [comment]
[amqp-client.js](https://github.com/cloudamqp/amqp-client.js) implements this pragmatically, set to zero on the client side means disable it. And amqp-client.js of course enables TCP keepalive, which is a much more reliable keepalive mechanism than AMQP heartbeats.
