### ISSUE TITLE
bindQueue lib/codec and arrays

### ISSUE THREAD

**Issue by daKuleMune** [amqp-node/amqplib#507]
When calling bind queue according to the documentation "bindQueue(queue, source, pattern, [args])" args is an array, however if there are any prototype additions on Array.prototype this will fail. TypeError: Unknown type to encode: function at encodeFieldValue (.../node_modules/amqplib/lib/codec.js:229:15). This appears to be because the array type is being interpreted as an object and then attempting to encode each property of including the functions.

**Comment by navstev0** [comment]
defs.js line 1446 in function encodeQueueBind is doing the following.
val = fields.arguments;
  if (void 0 === val) val = {}; else if ("object" != typeof val) throw new TypeError("Field 'arguments' is the wrong type; must be an object");
  len = encodeTable(SCRATCH, val, scratchOffset);
Because it is encoded this way it is going to catch on any prototype extensions. 
Seems strange but a quick fix keeping it working as is would be to put the following
```case 'function':
        break;```
in codec.js type case statement.

**Comment by LynxyssCZ** [comment]
In this case the notation means, taht the `args` is optional, there is just a typo and the signature should read `#bindQueue(queue, source, pattern [, args])`
Also, if you read on, there is
> args is an object containing extra arguments that may be required for the particular exchange type (for which, see your server’s documentation). It may be omitted if it’s the last argument, which is equivalent to an empty object.
