### ISSUE TITLE
Node express app crashes due to amqplib heartbeat bug

### ISSUE THREAD

**Issue by razcakappa** [amqp-node/amqplib#557]
I'm running a containerized Nodejs express app with amqplib in a production environment with lot less incoming traffic.
However after a 3-4 days continuous run, node service crashes by dumping below.
```
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: Heartbeat timeout
    at Heart.<anonymous> (/home/app/node_modules/amqplib/lib/connection.js:427:19)
    at Heart.emit (events.js:203:13)
    at Heart.runHeartbeat (/home/app/node_modules/amqplib/lib/heartbeat.js:88:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Emitted 'error' event at:
    at Connection.emit (events.js:203:13)
    at Heart.<anonymous> (/home/app/node_modules/amqplib/lib/connection.js:428:12)
    at Heart.emit (events.js:203:13)
    [... lines matching original stack trace ...]
    at processTimers (internal/timers.js:475:7)
[nodemon] app crashed - waiting for file changes before starting...
```

Any clues on debugging this would be wonderful.

**Comment by cressie176** [comment]
Hi @razcakappa,

The AMQP protocol supports bi-directional heartbeats so the client and server can monitor whether the connection gets dropped in an undetectable way (e.g. by a VPN) See [the documentation](https://www.rabbitmq.com/heartbeats.html) for details.

The three common reasons for seeing heartbeats are

1. The connection was dropped by intermediary service like a VPN or firewall, but without actually closing the connection.
2. Your event loop is getting saturated so the client cannot respond or detect heartbeats within the appropriate timeframe.
3. Your network is flakey

There are various node libraries for detecting whether your event loop is saturated (e.g. [blocked](https://www.npmjs.com/package/blocked) however I haven't used them and advise reading the documentation thoroughly in case they cause a performance problem. 

If it's not the event loop then I would be looking out for infrastructure components like firewalls, vpns. Failing that you could try tuning the heartbeat interval. You can also disable it at the broker end, but I wouldn't recommend this since you won't receive notification if the connection silently goes away.

The second part of this problem is how to recover if the heartbeat does time out (or any other channel / connection error for that matter). The simplest solution is to attempt to restart your application, but obviously this can be disruptive for inflight work. A more graceful, but harder option is to automatically reconnect, but this requires you to replace any channels and resubscribe any consumers, plus if the connection genuinely has gone you might want some kind of random backoff algorithm. I manage this in [rascal](https://github.com/guidesmiths/rascal) by using a channel pool for publishing, and having the pool replace borked channels / connections. For consumers I replace the connection, recreate the channel and resubscribe.

**Comment by cressie176** [comment]
Were you able to resolve the issue @razcakappa?

**Comment by razcakappa** [comment]
@cressie176 Well I'm middle of a desperation. I need my containers to be stateless. In mean time same container should handle a mission critical process which assigned through the queue. I'm still wondering how to tackle this. Any suggestions would be highly appreciated.

**Comment by cressie176** [comment]
Did you look into

* what the heartbeat timeout was set
* whether your event loop was being saturated

Did you look into handling the error event and either reconnecting/resubscribing or restarting your application?

**Comment by razcakappa** [comment]
Here's the current flow. 

- Currently the rabbitMQ server doesn't have any configured values. Since client doesn't request any heartbeat value upon connection, I assume, heartbeat is 60 (Server default)

- Event loop doesn't get blocked, however sometimes client faces critical low hardware resource availability due to some external services eat current resources.

- This is how I connect to rabbitMQ server. There's an catch block, however when heart beat times out there's an uncaught exception.

```javascript
  amqp.connect('amqp://rabbitmq-docker').then(function (conn) {

    process.once('SIGINT', function () { conn.close(); });

    /**
     *  my custom process upon incoming message
     */
    let Qname = process.env.QNAME;
    conn.createChannel().then(function (ch) {
      var ok = ch.assertQueue(Qname, { durable: false });
      ok = ok.then(function (_qok) {
        return ch.consume(Qname, async function (msg) {

          try {

            var g = msg.content.toString();
            var responce = JSON.parse(g);

            try {
              common_functions.updateTicketStatus(db, responce);
            } catch (error) {
              console.log(error);
            }

          } catch (error) {
            console.log('json parse error on user update', error);
          }

          console.log(" [x] Received '%s'", msg.content.toString());
        }, { noAck: true });
      });
      return ok.then(async function (_consumeOk) {
        console.log('Listening : ');
      });
    });
  }).catch((err) => {
    console.log('rabbitmq connection error', err);
  });
```

**Comment by cressie176** [comment]
You could try requesting a heartbeat of say 10 seconds. Heartbeats can act as a connection keep alive and prevent VPNs/Firewalls thinking the connection is inactive

Secondly you could add "error" and "close" event handlers to the connection and channel objects, e.g.

```connection.on('error', (err) => {
  // recover
});

channel.on('error', (err) => {
  // recover
});
```

This will stop your application from crashing, since without the handlers the error even bubbles up and kill the process. See [here](https://nodejs.org/docs/latest-v12.x/api/events.html#events_error_events).

The simplest recovery strategy is just to gracefully restart your application, because it means you'll automatically create the connection and reconsume from the queue again, but this obviously can be quite disruptive and not really any different from allowing it to crash. Alternatively you need to work out how you are going to reconnect / resubscribe, bearing in mind you could get multiple error events / close events from the connection and channel, and you might need to attempt recovery multiple times in the event of a genuine network or server error. This was one of the motivations behind [rascal](https://github.com/guidesmiths/rascal). Looking at the code might shed some light. It might also help to review this [example](https://github.com/cressie176/amqplib-express-example). It doesn't have a subscriber, but demonstrate registering the event handlers more clearly than the rascal code.
 
I also notice that your code does not handle a `null` message. You get one of these if the queue is deleted or the broker is gracefully restarted.

**Comment by cressie176** [comment]
Any luck @razcakappa?

**Comment by PeterMerkert** [comment]
I find myself in a similar spot. My production cluster starts throwing this error after a while. However, in my staging cluster I have not experienced any issues. Further, I am not experiencing problems with consumers, but with my API which is my publisher. I have two microservices each being a consumer which do not thrown any error.
I am running in Oracle Kubernetes Engine. I use CloudAMPQP to manage the queue.

The callstack does say mention as well only lines out of my reach:
```
Error: Heartbeat timeout
    at Heart.<anonymous> (/usr/src/app/node_modules/amqplib/lib/connection.js:427:19)
    at Heart.emit (events.js:203:13)
    at Heart.runHeartbeat (/usr/src/app/node_modules/amqplib/lib/heartbeat.js:88:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

I will add the event handler for the channel error. I had an event handler for the connection already and that did not get fired (as it would have been in the callstack then).

```js
const amqp = require('amqplib')
const async = require('async')
const config = require('../config')
const logger = require('../logger')
const {QueueError, QUEUE_NOT_INITIALIZED} = require('./http-errors')

const connectUrl = `amqp://${config.rabbitMq.user}:${config.rabbitMq.password}@${config.rabbitMq.host}/${config.rabbitMq.instanceName}`

let connection = null
let channel = null
const rabbitMQError = new Error('RabbitMQ')

module.exports.init = async () => {
  if (!connection) {
    try {
      connection = await async.retry(
        {
          times: 24,
          interval: retryCount => {
            logger.error(`[RabbitMQ] Connection could not be establish. Retry count ${retryCount}`)
            return 5000
          },
        },
        async () => amqp.connect(connectUrl)
      )
      logger.info('[RabbitMQ] Connection to queue established')
    } catch (error) {
      logger.error(error, '[RabbitMQ] Cannot connect to queue')
      throw rabbitMQError
    }

    try {
      logger.info('[RabbitMQ] Creating channel to publish')
      channel = await connection.createChannel()
    } catch (error) {
      channel = null
      logger.error(error, '[RabbitMQ] Failed to create channel')
      throw rabbitMQError
    }

    connection.on('error', error => {
      logger.error(error, '[RabbitMQ] Connection error occured')
      throw rabbitMQError
    })

    channel.on('error', error => {
      logger.error(error, '[RabbitMQ] Channel error occured')
    })
  }
}

module.exports.publish = async (msg, queueName) => {
  if (!connection) throw new QueueError(QUEUE_NOT_INITIALIZED)

  await channel.assertQueue(queueName)

  const data = Buffer.from(JSON.stringify(msg))
  channel.sendToQueue(queueName, data, {persistent: true})
}
```

Whereas, I call `init()` to initialise the queue once and `publish` somewhere in code to publish a message.
Do you see any obvious issues?

**Comment by cressie176** [comment]
@PeterMerkert 

This is what I get when I run your code with only inconsequential changes...
```
[RabbitMQ] Connection to queue established
[RabbitMQ] Creating channel to publish
Error: Heartbeat timeout
    at Heart.<anonymous> (/Users/steve/Development/cressie176/557/node_modules/amqplib/lib/connection.js:427:19)
    at Heart.emit (events.js:200:13)
    at Heart.runHeartbeat (/Users/steve/Development/cressie176/557/node_modules/amqplib/lib/heartbeat.js:88:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) [RabbitMQ] Connection error occured
/Users/steve/Development/cressie176/557/index.js:40
      throw rabbitMQError
```

Here's the script. To test I ran against a docker container, which I paused after the script had connected.

```js
const amqp = require('amqplib')
const async = require('async')

const connectUrl = `amqp://localhost:5672?heartbeat=5`

let connection = null
let channel = null
const rabbitMQError = new Error('RabbitMQ');

(async () => {
  if (!connection) {
    try {
      connection = await async.retry(
        {
          times: 24,
          interval: retryCount => {
            console.error(`[RabbitMQ] Connection could not be establish. Retry count ${retryCount}`)
            return 5000
          },
        },
        async () => amqp.connect(connectUrl)
      )
      console.info('[RabbitMQ] Connection to queue established')
    } catch (error) {
      console.error(error, '[RabbitMQ] Cannot connect to queue')
      throw rabbitMQError
    }

    try {
      console.info('[RabbitMQ] Creating channel to publish')
      channel = await connection.createChannel()
    } catch (error) {
      channel = null
      console.error(error, '[RabbitMQ] Failed to create channel')
      throw rabbitMQError
    }

    connection.on('error', error => {
      console.error(error, '[RabbitMQ] Connection error occured')
      throw rabbitMQError
    })

    channel.on('error', error => {
      console.error(error, '[RabbitMQ] Channel error occured')
    })
  }
})();

setInterval(() => {}, 1000000);
```

**Comment by PeterMerkert** [comment]
@cressie176 thanks for trying it out and confirming it.

I use [Pino](https://www.npmjs.com/package/pino) as logger. But for the test it obviously does not matter. Not sure why there are neither the `Connection error occured` nor the `Channel error occured` logs are coming through though.

Could be related to https://github.com/squaremo/amqp.node/issues/549 for me, because we use Node v13.9.0 and I did not pay attention to see the warning yet. With which Node version did you try it?

**Comment by cressie176** [comment]
I was using node 12, but get the same with 13.9.0

```
Now using node v13.9.0 (npm v6.13.7)
euphrosyne:557 steve$ rm -rf node_modules/
euphrosyne:557 steve$ npm install
npm WARN 557@1.0.0 No description
npm WARN 557@1.0.0 No repository field.

added 16 packages from 12 contributors and audited 18 packages in 1.154s
found 0 vulnerabilities

euphrosyne:557 steve$ node index.js 
[RabbitMQ] Connection to queue established
[RabbitMQ] Creating channel to publish
Error: Heartbeat timeout
    at Heart.<anonymous> (/Users/steve/Development/cressie176/557/node_modules/amqplib/lib/connection.js:427:19)
    at Heart.emit (events.js:321:20)
    at Heart.runHeartbeat (/Users/steve/Development/cressie176/557/node_modules/amqplib/lib/heartbeat.js:88:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) [RabbitMQ] Connection error occured
/Users/steve/Development/cressie176/557/index.js:40
      throw rabbitMQError
      ^
```

**Comment by cressie176** [comment]
With pino / pino-pretty I still get

```
euphrosyne:557 steve$ node index.js | pino-pretty
[1585202020038] INFO  (47346 on euphrosyne.local): [RabbitMQ] Connection to queue established
[1585202020040] INFO  (47346 on euphrosyne.local): [RabbitMQ] Creating channel to publish
[1585202035041] ERROR (47346 on euphrosyne.local): [RabbitMQ] Connection error occured
    Error: Heartbeat timeout
        at Heart.<anonymous> (/Users/steve/Development/cressie176/557/node_modules/amqplib/lib/connection.js:427:19)
        at Heart.emit (events.js:321:20)
        at Heart.runHeartbeat (/Users/steve/Development/cressie176/557/node_modules/amqplib/lib/heartbeat.js:88:17)
        at listOnTimeout (internal/timers.js:549:17)
        at processTimers (internal/timers.js:492:7)
/Users/steve/Development/cressie176/557/index.js:41
      throw rabbitMQError
      ^

Error: RabbitMQ
    at Object.<anonymous> (/Users/steve/Development/cressie176/557/index.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
I'm getting my logs from the console, but if yours are being written to disk it's possible the application is crashing before a buffer is flushed. However I have another theory...

Although I haven't seen [this problem](https://github.com/squaremo/amqp.node/issues/388) since 0.5.1, maybe async.retry is be causing multiple connections to the broker. If the connection takes too long to establish, amqplib would errored due to timeout. If the connection was eventually successful, async.retry would not resolve it, and your code would not add the customer error handler. Do you see any  `[RabbitMQ] Connection could not be establish. Retry count ${retryCount}` messages when your application was initialised?

**Comment by PeterMerkert** [comment]
Thanks again for all your time and effort!

With Pino you actually get the following line, which you did not get before:
`[1585202035041] ERROR (47346 on euphrosyne.local): [RabbitMQ] Connection error occured`.

I did not encounter that mentioned output about the retry in production consciously. However, our log retention is only 7 days and thus, I cannot tell you if that actually happened on our API pod half a month ago. So, could have been the case - I can unfortunately not tell you.

I actually just have the retry for local and test development since it then waits till my infrastructure is up and running.

**Comment by cressie176** [comment]
> With Pino you actually get the following line, which you did not get before:

It was there, but tagged onto the end of the previous stack...
```
    at processTimers (internal/timers.js:492:7) [RabbitMQ] Connection error occured
/Users/steve/Development/cressie176/557/index.js:40
```

**Comment by carlhoerberg** [comment]
I would recommend disabling AMQP heartbeats and instead enable TCP keepalive, it's the exact same mechanism, just that it's handled on the kernel level instead of in the application level which makes it a lot more reliable. The only "problem" is that specifying the intervals is different for each OS, and neither Erlang (RabbitMQ) nor nodejs has a way of setting the probe intervals in the application, so in this case you have to do it outside. In Linux you do it like this: 

```shell
sysctl -w \
  net.ipv4.tcp_keepalive_time=60 \
  net.ipv4.tcp_keepalive_intvl=10 \
  net.ipv4.tcp_keepalive_probes=3
```

That will send an ACK package every 60s, wait 10s, then send another if no reply is received, and then do that 3 times and if still no reply the connection is closed (RST) (so after 90s).

In RabbitMQ you enable keepalives with 
```
tcp_listen_options.keepalive = true
```
and configure the sysctl as above. 

At CloudAMQP we enable and recommend TCP keepalives over AMQP heartbeats because many times heartbeats causes more problems than it solves. 

Reference:
https://www.rabbitmq.com/networking.html#tcp-keepalives
https://nodejs.org/api/net.html#net_socket_setkeepalive_enable_initialdelay

**Comment by pchand89** [comment]
@razcakappa did u get the solutions for this issue? Im facing the same issue with node 12.18 and amqplib 0.5.6. I couldn't make out any conclusion out of this conversation thread. Please suggest solution if you have got one.

**Comment by razcakappa** [comment]
> @razcakappa did u get the solutions for this issue? Im facing the same issue with node 12.18 and amqplib 0.5.6. I couldn't make out any conclusion out of this conversation thread. Please suggest solution if you have got one.
@pchand89 
My problem was mainly based on lack of hardware resources to Rabbitmq server. 

I was running a docker-compose ochestrated container instances (few dozen) and most of the time when the memory hits the ceiling due to badly designed Nodejs services and overly complicated databases, most of the services tend to hangup for a moment and for the services like Rabbitmq which uses heartbeats (keep alives, beacons) those were in trouble. 

Once I throw some hardware resources and fixing/refactoring the resource hungry services, this heartbeat issue got less and less irritating. Now this happens very rarely. 

However I'll look in to ficing resource hungry services, increasing hardware resources, will be extra carefull on how many connections, channels are opened and are being re-used? Are you properly closing connections/channels? 

Also there are really good comments up top describing about the inner workings. However I hardly belive this is a bug.

**Comment by azickri** [comment]
@cressie176 , Can this code fix dead nodes caused by a Hearthbeat Error like this?
I don't know how to get the heartbeat error message.

```
connection.on('error', (err) => {
  // recover
});

channel.on('error', (err) => {
  // recover
});
```

Then how do you reconnect a dead connection?
Or do I need to, repeat like the `amqp.connect`?

![image](https://user-images.githubusercontent.com/45684749/213161168-e376b80c-e580-439f-84db-5727c493acef.png)
