### ISSUE TITLE
Memory leak by binding then remove Queue

### ISSUE THREAD

**Issue by qwertymypass** [amqp-node/amqplib#585]
Hello
If you create a queus, then create a binding and then delete a queu, you will see that the application memory grows, but if you unbind before deleting the queue, then the problem goes away, is this standard behavior?
There is an assumption that the bindings in the libraries are saved even after the queue is deleted, it seems to me this is a bug, because the binding to the queue should not be stored without this queue

**Comment by Uzlopak** [comment]
WHen you running two services, where both of the services are listening to the queue and one of the services deletes the queue, then the other consumer/other service will get a null msg in onMessage-Handler. Maybe there you should modify amqplib and remove the supposed binding to the queue in the node-memory.

**Comment by squaremo** [comment]
> If you create a queus, then create a binding and then delete a queu, you will see that the application memory grows

These are all records at the server, not at the client (i.e., not in amqplib). When you create a binding, there's no record of it kept in the client.

Can you post code that demonstrates the effect?

**Comment by squaremo** [comment]
> WHen you running two services, where both of the services are listening to the queue and one of the services deletes the queue, then the other consumer/other service will get a null msg in onMessage-Handler

As noted in https://www.squaremobius.net/amqp.node/channel_api.html#channel_consume, when a consumer is cancelled it gets a `null` message.

**Comment by Uzlopak** [comment]
@squaremo 

I think this describes actually the issue with the memory leak. 

When the queue gets deleted by a different channel then all the other consumers get the null message. AmqpLib does not check if the msg is null to determine that it has to call unregisterConsumer. So the consumer and the callback are still in the Channel.consumers Object and the memory is not freed.

Also you can not call unbindQueue from the onMessage-Callback, as the queue does not exist anymore. So you would probably bork the channel as unbindQueue would throw an Error. unregisterConsumer is also not exposed by the Channel... or atleast not in the @types/amqplib definitions.

And even if unregisterConsumer would be exposed then in the onMessage-Callback you dont have the consumerTag as the msg is null (so you can not determine the from msg.fields.consumerTag and it is not provided by the other parameters) to manually call .unregisterConsumer(consumerTag) to free up the memory. 

Maybe if you define the consumerTag above the .consume()-call and assign the returnValue (=consumerTag) of the consume-call in the upper scope, you could maybe use it in the onMessage-Callback to call unregisterConsumer. This could be still a memory leak as the string would be kept probably permanently, but it would have a smaller memory footprint then still having the consumerTag in the consumer-Object.

Like this (not tested):

```typescript
let consumerTag;

consumerTag = await channel.consume("a-queue", (msg) => {
   if (msg === null) {
       channel.unregisterConsumer(consumerTag);
       return;
   }
   // process msg as usual
}, {}).consumerTag;
```
 Also I think .cancel(), which calls unregisterConsumer, does not fit, as we would send another rpc to amqplib to stop consuming the the queue?! Supposedly when the queue gets deleted, the consumer gets terminated by rabbitmq - hence sending null to the consumer to tell it, that it got disconected?!

Or is this the prefered onMessage-Callback?:

```typescript
let consumerTag;

consumerTag = await channel.consume("a-queue", (msg) => {
   if (msg === null) {
       channel.cancel(consumerTag);
       return;
   }
   // process msg as usual
}, {}).consumerTag;
```

But it would be more elegant, if amqplib would do this by itself, instead of handling the unregisterConsumer in the null case by the implementor of the onMessage-Callback in the onMessage-Callback. The msg-null should still be passed through to the onMessage-Callback as you could still have the need to handle that case in a special way, like again asserting the queue and consume it again.

**Comment by Uzlopak** [comment]
Probably modifying dispatchMessage in channel.js like this, could solve the memory leak

https://github.com/squaremo/amqp.node/blob/b183cd8ac6776b41a1f3975465d2876252f226fb/lib/channel.js#L479
```
BaseChannel.prototype.dispatchMessage = function (fields, message) {
	var consumerTag = fields.consumerTag;
	var consumer = this.consumers[consumerTag];
	if (consumer) {
		consumer(message);
		// If the consumer is cancelled by RabbitMQ, the message callback will be invoked with null.
		// In this case, we unregister the consumer to prevent a memory leak with dead consumers.
		if (message === null) {
			this.unregisterConsumer(consumerTag);
		}
		return;
	}
	else {
		// %%% Surely a race here
		throw new Error("Unknown consumer: " + consumerTag);
	}
};
```

**Comment by Uzlopak** [comment]
Created now a PR. Instead of having the if-clause in dispatchMessage, I added it into handleCancel.

**Comment by Uzlopak** [comment]
Hi @squaremo 

I provided a PR for this bug more than a month ago. Would you please review?

**Comment by kibertoad** [comment]
@Uzlopak hello there! I'll take a look today :)
