### ISSUE TITLE
[Question] handle if exists connection

### ISSUE THREAD

**Issue by sptGabriel** [amqp-node/amqplib#586]
Hello I have a question about rabbitmq with amqplib

well I have a logic to retry the connection, but my question is regarding the connection.

Before trying to make the connection I do a validation if there is already an open connection, but I am in doubt of the correct way to do this:
```

  public start = async () => {
    if (this.connection || !this.rabbitUrl) return;
    this.connection = await retry<Connection>(
      () => connect(this.rabbitUrl),
      10,
      1000
    ).then((connection) => {
      Logger.info('connect to RabbitMQ success');
      return this.listeners();
    });
  };
```

my listeners:

```
 private listeners = (): Promise<Connection> => {
    return new Promise((resolve, reject) => {
      if (!this.connection) {
        this.rabbitUrl ? this.start() : reject();
        reject();
      }
      resolve(
        this.connection.on('error', (err: Error) => {
          Logger.info(err.message);
          sleep(this.start, 10000);
        }) &&
          this.connection.on('close', (err: Error) => {
            if (err) {
              Logger.info('connection closed because err!');
              sleep(this.start, 10000);
            }
            Logger.info('connection to RabbitQM closed!');
          })
      );
    });
  };
```

at the moment if there is no connection I just use return, I have doubts if the correct one would throw an error informing that there is already a connection, or would just return with a logger be the correct one? Which of these two ways is correct with respect to performance and does not compromise the flow?

**Comment by cressie176** [comment]
Closing as too old. For anyone reaching this issue in future I would suggest...

1. Only establishing consumers / publishers after establishing the necessary connections and channels
2. Using the connection and channel error/close events to know when connection and channels are open
3. Carefully controlling the sequence of channel operations so that your application does not attempt to use a recently closed connection or channel
4. Watching out for null messages which indicate a cancelled consumer
