### ISSUE TITLE
How to handle publish false return using drain event?

### ISSUE THREAD

**Issue by amitagarwal-dev** [amqp-node/amqplib#669]
In my code publish function is returning false in high load situation, i know the reason and it can be prevented by tracking drain event
but how to use this drain when we get false for very first time?  
  
As per the doc:  
`Channels act like [stream.Writable] when you call publish or sendToQueue: they return either true, meaning “keep sending”, or false, meaning “please wait for a ‘drain’ event”.`  

So if the return value is false means i can do following thing below.  
```
let ret = Publish(...);

if( !ret ){
channel.once('drain',()=>{
 Publish(...); // confusion is here, whether i need to publish again or it will automatically publish the last one?
})
}
else{
return;
}
```

Any clue here?

**Comment by cressie176** [comment]
Hi @amitagarwal-dev, you don't need to republish the message, but it is good practice to back off from attempting to publish more until you receive a drain event.

**Comment by amitagarwal-dev** [comment]
Hi @cressie176, so what will happen to that last message for which i was getting false from publish function? Is it accepted by rabbitmq and will be taken care by rabbitmq once drain event is generated or i have to handle that last message by republishing it by myself.  
  
This drain event is a client side event right, it is not coming from rabbitmq or is it? I am little bit confused in drain and blocked event. Do you have any example or doc for reference? As you are telling to stop the further publish but in my case i can't stop my server for accepting request, so publish will happen continuously, i can keep those false returned messages in program memory till drain event is generated but as you are telling that we don't need to republish then how to handle this scenario?

**Comment by cressie176** [comment]
Hi @amitagarwal-dev,

When you get `false` it means that you are attempting to publish messages faster than RabbtiMQ can receive them. If this continues, eventually the client process will run out of memory and crash, losing any unconfirmed messages. Furthermore, If you are not sending the HTTP response until after you receive a publish confirmation, then each message will take longer and longer, eventually leading to the HTTP client timing out. If you are unable to back-off, then immediately telling the HTTP client to back-off by sending a 503 - Service Unavailable rather than handling the request, until your receive the drain event is something to consider.

However, unless your process crashes the messages will not be lost, since publish will still buffer the message even when it returns false. You may find the following comment helpful. https://github.com/amqp-node/amqplib/issues/398#issuecomment-350860245

I haven't done very much with the blocked event, but would guess you can ignore it, since if the connection is blocked, the buffer should fill, and you will start receiving `false` from publish operations.

**Comment by amitagarwal-dev** [comment]
Hi @cressie176 ,  
  
So i added 503 once i am getting false from publish and , as per you the amqp client library will automatically buffer all the messages which got false from publish right.

**Comment by cressie176** [comment]
Correct. And of course once you get the "drain" event you would start accepting HTTP requests again rather than returning 503s

**Comment by amitagarwal-dev** [comment]
Thanks for the clarification @cressie176
