### ISSUE TITLE
[RabbitMQ] Error: Frame size exceeds frame max

### ISSUE THREAD

**Issue by romatallinn** [amqp-node/amqplib#693]
Connection to RabbitMQ fails with `Error: Frame size exceeds frame max`.

Although there are a few similar issues raised on StackOverflow and Github (#560, #462), but it is still very vague.

One assumes that the version of AMQP used by RabbitMQ and amqplib differs, but how to check that? If talking about major differences between `amqp 1.0` and `amqp 0-9-1`, then theoretically amqplib only supports 0-9-1 and RabbitMQ supports it by default.

Any ideas on how to pinpoint the problem?

Versions:
- RabbitMQ: 3.10.5
- amqplib: 0.10.0

**Comment by cressie176** [comment]
Hi @romatallinn,

This [error](https://github.com/amqp-node/amqplib/blob/243aef8b6da766a3b9908bc50b2be4859eef43a6/lib/frame.js#L55) occurs when amqplib attempts to parse a frame sent by the server that is too big. I believe the max frame size starts off as 4096 bytes but can be increased during the connection handshake by way of the frameMax query parameter passed to [amqplib.connect](https://amqp-node.github.io/amqplib/channel_api.html#connect), e.g.

```js
const amqplib = require('amqplib');
amqplib.connect('amqp://localhost:5672?frameMax=0x8000')
```
However, I. think frameMax is likely to be a red herring, since you say the problem occurs on connection, and this only affects communication after the connection has been established.

You mention amqp 1.0, which RabbitMQ only supports via a [plugin](https://github.com/rabbitmq/rabbitmq-server/tree/master/deps/rabbitmq_amqp1_0). amqplib does not support 1.0 so if you have enabled the plugging and are trying to use 1.0, then I suspect his is your problem.

Alternatively, is it possible that you are connecting to something else other than RabbitMQ? Could you have specified the wrong port, or has another server grabbed the port your are expecting as per https://github.com/amqp-node/amqplib/issues/560?

Deliberately connecting to an HTTP server will reproduce the error, e.g.

```js
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect('amqp://example.com:80');
  await connection.close();  	
})();
```

```
Error: Frame size exceeds frame max
```

Failing that I suggest debugging with [wireshark](https://www.rabbitmq.com/amqp-wireshark.html).  You should see something like the following...

<img width="955" alt="Screenshot 2022-07-05 at 09 14 19" src="https://user-images.githubusercontent.com/229672/177271266-1adb55de-9eef-4678-b66f-cd741498f5ad.png">

It's also worth take a look at the Connection.Tune and Connection.Tune-OK in case there's something odd. For the script above mine are

Connection.Tune-OK
```
Frame 11: 96 bytes on wire (768 bits), 96 bytes captured (768 bits) on interface lo0, id 0
Null/Loopback
Internet Protocol Version 6, Src: ::1, Dst: ::1
Transmission Control Protocol, Src Port: 5672, Dst Port: 50866, Seq: 517, Ack: 331, Len: 20
Advanced Message Queueing Protocol
    Type: Method (1)
    Channel: 0
    Length: 12
    Class: Connection (10)
    Method: Tune (30)
    Arguments
        Channel-Max: 2047
        Frame-Max: 131072
        Heartbeat: 60
```

Connection.Tune-OK
```
Frame 13: 96 bytes on wire (768 bits), 96 bytes captured (768 bits) on interface lo0, id 0
Null/Loopback
Internet Protocol Version 6, Src: ::1, Dst: ::1
Transmission Control Protocol, Src Port: 50866, Dst Port: 5672, Seq: 331, Ack: 537, Len: 20
Advanced Message Queueing Protocol
    Type: Method (1)
    Channel: 0
    Length: 12
    Class: Connection (10)
    Method: Tune-Ok (31)
    Arguments
        Channel-Max: 2047
        Frame-Max: 4096
        Heartbeat: 60
```

**Comment by cressie176** [comment]
Any luck @romatallinn?
