### ISSUE TITLE
RPC - Direct reply mode

### ISSUE THREAD

**Issue by esellier** [amqp-node/amqplib#709]
Hello,

The Queue name should be the pseudo queue "amq.rabbitmq.reply-to", not "".
This prevents creating a dedicated queue, and use an exchange, routed directly to the RPC client when RPC server replies.
https://github.com/amqp-node/amqplib/blob/b98228f5974de6943e72c6e90bd357a4101956bf/examples/tutorials/rpc_client.js#L32

See documentation there : https://www.rabbitmq.com/direct-reply-to.html

Thanks

**Comment by cressie176** [comment]
Hi @esellier,

Thank you for raising. I'll take a closer look a bit later, but it looks to me like the referenced example is following the RabbitMQ [PRC tutorial](https://www.rabbitmq.com/tutorials/tutorial-six-javascript.html) which asserts an exclusive queue with server allocated name, rather than being an example of RabbitMQ's direct reply to feature, which is something slightly different.

> This prevents creating a dedicated queue, and use an exchange, routed directly to the RPC client when RPC server replies.

I'm sorry, but I don't follow. Can you explain again what is prevented?

Thank you

**Comment by esellier** [comment]
Hi Cressie,

In your example, as you give an empty name, RabbitMQ will give it a name and create a queue.
When using the "amq.rabbitmq.reply-to" pseudo queue, there is no queue created. I suppose it's faster and lighter for the RabbitMQ node.
Since Direct-Reply works for RPC in a much efficient way, I would then recommend using this pseudo queue.
But maybe I'm wrong... :-) 

Emmanuel

**Comment by cressie176** [comment]
There are a [number of limitations](https://www.rabbitmq.com/direct-reply-to.html#limitations) that may mean direct-reply is not always the best option, although I agree it is a lighter approach. The examples are ports of the RabbitMQ tutorials, so I wouldn't change the example based on tutorial 6, but think it would be reasonable to add a specific direct-reply example.

**Comment by cressie176** [comment]
I've added an explicit direct reply to example
