### ISSUE TITLE
Error emitted before handler is attached causes "Unhandled 'error' event"

### ISSUE THREAD

**Issue by voztaka** [amqp-node/amqplib#738]
### Overview
When initiating a connection with amqplib, there's a scenario where an error can be emitted on the connection object before the error handler has been attached. This is particularly evident when simulating a "Heartbeat timeout" in the amqplib module.

### Steps to reproduce:
1. Modify the connection.js in the amqplib module to force a heartbeat error:
```
C.startHeartbeater = function() {
  var self = this;
  var hberr = new Error("Heartbeat timeout");
  self.emit('error', hberr);

  // ... rest of the code ...
};
```

2. Use the provided code to initiate a connection and attach an error handler:
```
const amqp = require("amqplib/callback_api");

amqp.connect("amqp://localhost?heartbeat=60", (err, connection) => {
  connection.on("error", (err) => {
    console.error("Connection error:", err.stack);
  });

  if (err) throw err;

  connection.createChannel((err, channel) => {
    if (err) throw err;

    channel.on("error", (err) => {
      console.error("Channel error:", err.stack);
    });

    const queue = "hello";
    const msg = "Hello World!";

    channel.assertQueue(queue, {
      durable: false,
    });

    channel.sendToQueue(queue, Buffer.from(msg));
    console.log(" [x] Sent %s", msg);
  });

  setTimeout(() => {
    connection.close();
    process.exit(0);
  }, 500);
});
```

3. Run the script.

### Expected result:
The error handler attached to the connection object should catch the emitted error and log it.

### Actual result:
Node.js throws an unhandled 'error' event, crashing the application with the message:

```
Copy code
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: Heartbeat timeout
```

### Additional information:
amqplib version: ^0.10.3
Node.js version: v18.17.0
OS/Environment: windows10

**Comment by cressie176** [comment]
Hi @voztaka,

I've taken a brief look through the connect code, but ~don't see anywhere~ only see [one place](https://github.com/amqp-node/amqplib/blob/main/channel_api.js#L6-L8) where that the code yields to the event loop after establishing the socket, without an error handler being added. The flow is quite complicated though so I could have missed something. What I see is as follows...

1. Everything starts by calling [amqplib.connect](https://github.com/amqp-node/amqplib/blob/main/callback_api.js#L8)
2. This [delegates](https://github.com/amqp-node/amqplib/blob/main/callback_api.js#L14) to the [connect](https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L89) function in `./lib/connect`, which takes an `openCallback`.
3. The connect function tries to [establish](https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L165) a socket. If this succeeds the [onConnect](https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L143) callback is invoked. If it fails, an error is emitted which is [handled](https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L182-L184) and the error passed to the afore mentioned `openCallback`. While this code appears several lines after attempting to connect the socket, because the code is synchronous the handler will be registered before the socket can emit an error. I assume it is not possible for the socket to emit multiple errors though.
4. If the socket is established, the [onConnect](https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L143) initiates the handshake with the RabbitMQ broker by calling [open](https://github.com/amqp-node/amqplib/blob/main/lib/connect.js#L149)
5. The [open function](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L90) consistently uses the [bail function](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L123-L125) to yield errors, never emitting them. It also [registers](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L222) an error handler on the underlying stream to redirect error events to bail.
6. After the [handshake completes](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L190), the hearbeater is [started](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L209), which will [emit an error](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L375) if the timeout is exceeded, however this would require the code go asynchronous first, which it never does.
7. This stream error handler is [removed](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L226) and [replaced](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L227) just prior to the [openCallback](https://github.com/amqp-node/amqplib/blob/main/lib/connection.js#L232) being invoked, but again the code never goes asynchronous, so an error cannot be emitted before the connection is returned to the calling code.

All of the above looks fine, with the exception of when using the promise API, which will yield before returning the result of the [connect function](https://github.com/amqp-node/amqplib/blob/main/channel_api.js#L7), however your example code wasn't using the promise api.

Were you by any chance attempting to use node breakpoints / debug when you came across this issue?

**Comment by cressie176** [comment]
To revisit, there are two variables which have the potential to emit an error event

1. The socket
2. The connection

To test whether there are any real world scenarios where an event emitted by these objects is not routed either to the connect callback, or could not be handled by a custom handler added to the connection after the connect callback is called, I went through the amqplib code and forced an error to be emitted at various stages of the workflow and tested with the following code...

```js
const amqplib = require('amqplib/callback_api');

amqplib.connect('amqp://localhost:5672?heartbeat=30', (err, connection) => {
  if (err) {
    console.log('Caught Error', { err })
    process.exit(0);
  }
  connection.on('error', (error) => {
    console.log('Handled Connection Error', { error });
    process.exit(0);
  });
  console.log('OK');
});
```

The difference between my and your test is that where I emitted an error event from the connection, I wrapped the statement in a `setInterval` call to force it to run asynchronously, thus allowing any synchronous code to complete first, thus giving the custom error handler a chance to be added. i.e.

```js
setImmediate(() => {
  self.emit('error', new Error('Oh Noes!'));
});

The hearbeat function uses setInterval, and so would behave in the same way.

All emitted errors were either routed to the connect callback as expected, or were not emitted until after the bespoke error handler was added to the connection.

I rewrote my test to use the promises API and got the same results.

**Comment by cressie176** [comment]
OK to close @voztaka?
