### ISSUE TITLE
global prefetch become 0 if per-consume prefetch set

### ISSUE THREAD

**Issue by soryy708** [amqp-node/amqplib#743]
With the following environment:

- `RabbitMQ 3.10.2`
- `Erlang 24.3.4`
- (Docker image: `rabbitmq:3.10.2-management`)

Run this MCVE:

```typescript
import * as amqp from "amqplib";

(async () => {
  const connection = await amqp.connect({
    protocol: "amqp",
    hostname: "localhost",
    port: 5672,
    username: "...", // set this
    password: "...", // set this
  });
  const channel = await connection.createChannel();
  channel.prefetch(42, true);
  const { queue } = await channel.assertQueue("", { autoDelete: true });
  channel.prefetch(100, false);
  channel.consume(queue, () => null, { noAck: true });
})();
```

While this is running, go to [RabbitMQ management plugin UI](http://localhost:15672/#/channels/) and look at this channel:

![image](https://github.com/amqp-node/amqplib/assets/2157782/c1b79f20-26aa-413f-97e9-3cc5922cb671)

Expected:

We should see *prefetch*=100 for the consume, and *global prefetch*=42.

Actual:

Here we see the consume has *prefetch*=100 (as expected), but the *global prefetch* is 0 (but we expected what we have previously set it to 42).

**Comment by soryy708** [comment]
If we comment out the per-consume prefetch like so:

```typescript
import * as amqp from "amqplib";

(async () => {
  const connection = await amqp.connect({
    protocol: "amqp",
    hostname: "localhost",
    port: 5672,
    username: "balanceAdmin",
    password: "Aa123456",
  });
  const channel = await connection.createChannel();
  channel.prefetch(42, true);
  const { queue } = await channel.assertQueue("", { autoDelete: true });
  // channel.prefetch(100, false);
  channel.consume(queue, () => null, { noAck: true });
})();
```

then global prefetch is set as expected:

![image](https://github.com/amqp-node/amqplib/assets/2157782/433a7de5-5d57-4111-ab44-6290b78d0383)

but per-consume prefetch is 0.

**Comment by cressie176** [comment]
Hi @soryy708

I've run your code through WireShark and see the following

```
  channel.prefetch(42, true);
```

```
Advanced Message Queueing Protocol
    Type: Method (1)
    Channel: 1
    Length: 11
    Class: Basic (60)
    Method: Qos (10)
    Arguments
        Prefetch-Size: 0
        Prefetch-Count: 42
        .... ...1 = Global: True
```

```
channel.prefetch(100, false);
```

```
Advanced Message Queueing Protocol
    Type: Method (1)
    Channel: 1
    Length: 11
    Class: Basic (60)
    Method: Qos (10)
    Arguments
        Prefetch-Size: 0
        Prefetch-Count: 100
        .... ...0 = Global: False
```

So it looks like amqplib is sending the correct commands and arguments to the broker.

My best guess for what you're seeing in the management UI is that the channel's "prefetch count" and "global prefetch count" are the values that will be applied to subsequent consumer(s) that are created using this channel. Even if true, this is still misleading though since the [RabbitMQ documentation](https://www.rabbitmq.com/consumer-prefetch.html#sharing-the-limit) states when both per-channel (global = true) and per-consumer (global = false) are set, both values are honoured.

> The AMQP 0-9-1 specification does not explain what happens if you invoke basic.qos multiple times with different global values. RabbitMQ interprets this as meaning that the two prefetch limits should be enforced independently of each other; consumers will only receive new messages when neither limit on unacknowledged messages has been reached.

I think this one is for the [RabbitMQ team / community](https://www.rabbitmq.com/#community).
