### ISSUE TITLE
ERR_SSL_EMS_NOT_ENABLED

### ISSUE THREAD

**Issue by mateBe95** [amqp-node/amqplib#748]
err: {"library":"Provider routines","reason":"ems not enabled","code":"ERR_SSL_EMS_NOT_ENABLED"}
rabbit-clientCould not create the RabbitMQ connection. C0C71851527F0000:error:1C8000E9:Provider routines:kdf_tls1_prf_derive:ems not enabled:providers/implementations/kdfs/tls1_prf.c:200:
Failed to establish connection to RabbitMQ service.
Error: Could not create the RabbitMQ connection. C0C71851527F0000:error:1C8000E9:Provider routines:kdf_tls1_prf_derive:ems not enabled:providers/implementations/kdfs/tls1_prf.c:200:

  - amqplib 0.10.3
  - nodejs 18.18.2

**Comment by cressie176** [comment]
Hi @mateBe95,

Looks like you're attempting to use amqplib to connect to the broker using TLS. I'm not familiar with EMS (Extended Master Secret) however error appears to be coming from a c routine, so occurring at a lower level than this library. My first guess would be that there's something with the host or broker configuration / setup which is causing this. Possibly relating to old versions of TLS / operating system restrictions.

**Comment by cressie176** [comment]
Have you tried setting the minVersion in the amqplib socket options?

> minVersion [<string>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) Optionally set the minimum TLS version to allow. One of 'TLSv1.3', 'TLSv1.2', 'TLSv1.1', or 'TLSv1'. Cannot be specified along with the secureProtocol option; use one or the other. Avoid setting to less than TLSv1.2, but it may be required for interoperability. Default: [tls.DEFAULT_MIN_VERSION](https://nodejs.org/api/tls.html#tlsdefault_min_version).

See https://nodejs.org/api/tls.html and https://amqp-node.github.io/amqplib/ssl.html

**Comment by cressie176** [comment]
I'm not sure whether the broker (or potentially a proxy) is running a version of TLS which doesn't support Extended Master Socket, or if it is the client which doesn't. There are some commands in the [RabbitMQ SSL Troubleshooting Guide](https://www.rabbitmq.com/troubleshooting-ssl.html) which might help diagnose further

**Comment by cressie176** [comment]
I've revised my theory. Extended Master Secret (EMS) looks like is was a feature added to TLS1.2. It should be transparently negotiated between client and server.

The error code ERR_SSL_EMS_NOT_ENABLED appears to be [dynamically generated by Node](https://github.com/nodejs/node/blob/2d74e776ca8efc044b178620edb021a400fdce17/src/crypto/crypto_util.cc#L489-L492) from the reason string after a TLS error.

This implies that it is the client side which is reporting the error, but I'm still not sure if it because the client wants EMS and the broker doesn't have it, or vice versa. Some version of RedHat Enterprise (and possibly other distributions) require EMS to be enabled, particularly when running in a high security mode, e.g. [FIPS](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sect-security_guide-federal_standards_and_regulations-federal_information_processing_standard)

My next step would be to attempt to connect to the broker using `openssl s_client -connect` command as shown in the [RabbitMQ SSL TroubleshootingGuide](https://www.rabbitmq.com/troubleshooting-ssl.html)

**Comment by mateBe95** [comment]
@cressie176 yes exactly i want to run it in FIPS ubi-9 redhat image. Without fips configured it works as expected.

I have tried to use  update-crypto-policies --set FIPS:NO-ENFORCE-EMS but still the same error occurs.
https://www.redhat.com/en/blog/tls-extended-master-secret-and-fips-rhel

**Comment by cressie176** [comment]
I'm not sure there's anything amqplib can do about this. You can specify any socket options as part of the connect call, but from what I've read, it seems like EMS use is negotiated transparently as part of the TLS handshake. I'd still be interested to try using the openssl client to check the TSL the broker is using. If it shows EMS is disabled, it might be advantages to enable it and avoid the potential for a man-in-the-middle attack

**Comment by cressie176** [comment]
@mateBe95 don't think there's anything more I can do to help on this one. OK to close?
